version: '3.8'

services:
  jupyter:
    image: bagroo/xtts-python-3.11:latest
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
    command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
